Add indicator templates downloader command
tech-acs/chimera-starter-kit pull request #29
Opened 2022-11-19 11:53 UTC by baakal

*add console command to download latest release from git repositories into storage disk indicator_templates.

`php artisan chimera:install-indicator-templates`

*modify makeIndicator to use storage disk for creating new indicators

*change template stub to use parent_class alias for extensions

2022-11-19 13:44 UTC, amestsantim requested changes
Please make the suggested changes and then I can merge it
Thanks!

2022-11-19 13:44 UTC, amestsantim commented on deploy/commands/InstallIndicatorTemplates.php
> +    protected $signature = 'chimera:install-indicator-templates
I think it should be chimera:download-indicator-template and not install... Clearly, this command only downloads it and leaves it there, it is rather the make command that installs the template (by copying it in to App\IndicatorTemplates).

2022-11-19 13:44 UTC, amestsantim commented on deploy/commands/InstallIndicatorTemplates.php
> +    protected $description = 'Install indicator templates from the repository to the local storage';
Same as above. Download not install.

2022-11-19 13:44 UTC, amestsantim commented on deploy/commands/InstallIndicatorTemplates.php
> +        $url = config('chimera.indicator_template.url','https://api.github.com/repos/tech-acs/chimera-indicator-templates/');
I suggest chimera.indicator_template.repository_url or source_url

2022-11-19 13:44 UTC, amestsantim commented on deploy/commands/InstallIndicatorTemplates.php
> +            $url .= self::RELEASE_BY_TAG_API. $this->option('tag');
Please run cs fixer.
You're missing a space before the concatenation...

2022-11-19 13:44 UTC, amestsantim commented on deploy/commands/InstallIndicatorTemplates.php
> +        else{
This is not PSR-12 compliant.
And go for "early returns"

2022-11-19 13:44 UTC, amestsantim commented on deploy/commands/InstallIndicatorTemplates.php
> +        $destination_path = Storage::disk('indicator_templates')->path('');
You can use the zip:// protocol to access files directly inside the archive
https://www.tutorialspoint.com/how-to-read-a-single-file-inside-a-zip-archive-with-php

2022-11-21 03:12 UTC, baakal commented on deploy/commands/InstallIndicatorTemplates.php
> +        $destination_path = Storage::disk('indicator_templates')->path('');
recommend to implement this on a later version, we could look into zip:// protocol together.

2022-11-21 03:58 UTC, amestsantim approved these changes

2022-11-21 03:59 UTC, merged