Add Dockerization command
tech-acs/chimera-starter-kit pull request #9
Opened 2022-03-08 08:23 UTC by baakal

Add configuration files for dockerize in runtimes
Add stub for postgres and redis options
Add docker-compose generator artisan comand

2022-03-09 05:07 UTC, amestsantim requested changes

2022-03-09 05:07 UTC, amestsantim commented on docker/runtimes/Dockerfile
> +ARG OS_VERSION=3.14
the docker/runtimes directory seems to hold duplicate files that already exist in the docker directory... should it not have been committed or is it intentional?

2022-03-09 05:07 UTC, amestsantim commented on docker/runtimes/config/php.ini
> +[PHP]
I would also increase the default memory limit of 512MB

memory_limit = 512M

Perhaps you could request it from the user or something... 512MB is never enough for the dashboard and you'll run into out of memory errors in no time

2022-03-09 05:07 UTC, amestsantim commented on src/ChimeraStarterKitServiceProvider.php
> +            ->hasCommands([Chimera::class,Dockerify::class])
I don't think you need to add the command here. Just put it in the deploy/commands directory so that it gets copied into the spun-up dashboard where it will be available for use. The reason to add it here is to only make it available in the context of the package and not the resulting dashboard application.

2022-03-09 05:07 UTC, amestsantim commented on src/Commands/Dockerify.php
> +<?php
I'd name this command file (and class name) Dockerize, just to be consistent.

2022-03-09 13:27 UTC, baakal commented on src/ChimeraStarterKitServiceProvider.php
> +            ->hasCommands([Chimera::class,Dockerify::class])
This is intentional, the reason I have it here is because it will keep the spunned-up dashboard clean, it is a one time use code technically.

2022-03-09 13:33 UTC, baakal commented on docker/runtimes/Dockerfile
> +ARG OS_VERSION=3.14
Correct they were not suppose to be commited, will correct and push

2022-03-10 04:38 UTC, amestsantim commented
I'm closing it so that you can make the changes and send a new pull request.

2022-03-10 04:38 UTC, closed without merging